"""Record-family conformance: families B, C and ``purge_orphan`` (#631 WS3a).

Every test here runs on every configured backend with the *same* assertions:
``RedisBackend`` is the oracle (its bodies are today's code, moved verbatim in
WS0), so whatever it returns is what ``PostgresBackend`` must return. The
increment table below was generated by running the Redis path and recording
the return value and the stored bytes; the Redis leg re-validates the table
on every run and the Postgres leg is held to it.

Two helpers reach past the protocol: ``seed_index`` and ``index_has`` put a
member into a sorted or set index (Redis: ``ZADD``/``SADD`` on the plugin-bound
client; Postgres: a row in ``popoto_sorted``/``popoto_set`` through the
backend's own connection). ``purge_orphan`` needs an orphaned membership to
prune and the protocol methods that would create one (``sorted_add``,
``index_add``) are WS3b's, still stubs on Postgres.

Never touches database 0 or schema ``public``: the Redis leg goes through the
plugin-bound client and the Postgres leg through the harness's own schema.
"""

from __future__ import annotations

import struct
import threading
import time
from decimal import Decimal
from typing import Any

import msgpack
import pytest

from popoto.backends import postgres as postgres_module
from popoto.backends.postgres import PostgresBackend
from popoto.backends.redis import RedisBackend

pytestmark = pytest.mark.conformance

PREFIX = "popoto_test:631:records"
CLASS_SET = f"$Class:{PREFIX}:Record"


def key(suffix: Any) -> str:
    return f"{PREFIX}:Record:{suffix}"


def seed_index(backend: Any, idx: str, kind: str, member: str) -> None:
    """Put ``member`` into index ``idx`` outside the protocol (see module doc)."""
    if isinstance(backend, RedisBackend):
        if kind == "sorted":
            backend.client.zadd(idx, {member: 1.0})
        else:
            backend.client.sadd(idx, member)
        return
    assert isinstance(backend, PostgresBackend)
    conn = backend._connection()
    if kind == "sorted":
        conn.execute(
            "INSERT INTO popoto_sorted (idx, member, score) VALUES (%s, %s, 1.0) "
            "ON CONFLICT DO NOTHING",
            (idx, member),
        )
    else:
        conn.execute(
            "INSERT INTO popoto_set (idx, member) VALUES (%s, %s) "
            "ON CONFLICT DO NOTHING",
            (idx, member),
        )


def index_has(backend: Any, idx: str, kind: str, member: str) -> bool:
    if isinstance(backend, RedisBackend):
        if kind == "sorted":
            return backend.client.zscore(idx, member) is not None
        return bool(backend.client.sismember(idx, member))
    assert isinstance(backend, PostgresBackend)
    table = "popoto_sorted" if kind == "sorted" else "popoto_set"
    row = (
        backend._connection()
        .execute(f"SELECT 1 FROM {table} WHERE idx = %s AND member = %s", (idx, member))
        .fetchone()
    )
    return row is not None


# -- B. Records -----------------------------------------------------------------


class TestSaveAndLoad:
    def test_roundtrip_is_byte_identical_with_bytes_field_names(self, backend):
        fields = {
            b"name": msgpack.packb("alice"),
            b"blob": b"\x00\xff\xfe\x80",
            b"legacy\x00idxset": b"\x01",
        }
        assert backend.save_record(key(1), fields, class_set=CLASS_SET) == 3
        loaded = backend.load_record(key(1))
        assert loaded == fields
        assert all(isinstance(name, bytes) for name in loaded)
        assert all(isinstance(value, bytes) for value in loaded.values())

    def test_str_field_names_come_back_as_bytes(self, backend):
        backend.save_record(key(1), {"n": b"\x01"}, class_set=CLASS_SET)
        assert backend.load_record(key(1)) == {b"n": b"\x01"}

    def test_save_merges_fields_like_hset(self, backend):
        assert (
            backend.save_record(key(1), {b"a": b"1", b"b": b"2"}, class_set=CLASS_SET)
            == 2
        )
        # One new field, one re-written: the reply counts only the new one.
        assert (
            backend.save_record(key(1), {b"a": b"1", b"c": b"3"}, class_set=CLASS_SET)
            == 1
        )
        assert backend.load_record(key(1)) == {b"a": b"1", b"b": b"2", b"c": b"3"}

    def test_save_with_no_fields_only_registers_the_class_set(self, backend):
        # The EVAL-only path: the reply is then the SADD reply.
        assert backend.save_record(key(1), {}, class_set=CLASS_SET) == 1
        assert backend.save_record(key(1), {}, class_set=CLASS_SET) == 0
        assert backend.load_record(key(1)) is None
        assert backend.list_keys(CLASS_SET) == {key(1)}

    def test_a_missing_record_loads_as_none(self, backend):
        assert backend.load_record(key("missing")) is None

    def test_load_records_keeps_order_and_duplicates_with_none_for_missing(
        self, backend
    ):
        one = {b"a": b"1"}
        two = {b"b": b"2", b"c": b"\x00"}
        backend.save_record(key(1), one, class_set=CLASS_SET)
        backend.save_record(key(2), two, class_set=CLASS_SET)
        got = backend.load_records([key(2), key("missing"), key(1), key(2)])
        assert got == [two, None, one, two]
        assert got[0] is not got[3], "one dict per position, as HGETALL replies"
        assert backend.load_records([]) == []

    def test_load_fields_single_many_and_missing(self, backend):
        backend.save_record(key(1), {b"a": b"1", b"c": b"3"}, class_set=CLASS_SET)
        assert backend.load_fields(key(1), ["a"]) == [b"1"]
        assert backend.load_fields(key(1), ["a", "zz", "c"]) == [b"1", None, b"3"]
        assert backend.load_fields(key("missing"), ["a"]) == [None]
        assert backend.load_fields(key("missing"), ["a", "b"]) == [None, None]
        with pytest.raises(ValueError):
            backend.load_fields(key(1), [])

    def test_record_exists_and_class_set_bookkeeping(self, backend):
        assert not backend.record_exists(key(1))
        assert backend.list_keys(CLASS_SET) == set()
        assert backend.count_records(CLASS_SET) == 0
        backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET)
        backend.save_record(key(2), {b"a": b"1"}, class_set=CLASS_SET)
        assert backend.record_exists(key(1))
        assert backend.list_keys(CLASS_SET) == {key(1), key(2)}
        assert backend.count_records(CLASS_SET) == 2
        assert backend.count_records(f"{CLASS_SET}:nope") == 0

    def test_delete_record_returns_whether_it_existed(self, backend):
        backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET)
        assert backend.delete_record(key(1), class_set=CLASS_SET) is True
        assert backend.delete_record(key(1), class_set=CLASS_SET) is False
        assert backend.load_record(key(1)) is None
        assert not backend.record_exists(key(1))
        assert backend.list_keys(CLASS_SET) == set()
        assert backend.count_records(CLASS_SET) == 0

    def test_obsolete_key_is_migrated_out(self, backend):
        backend.save_record(key("old"), {b"a": b"1"}, class_set=CLASS_SET)
        reply = backend.save_record(
            key("new"), {b"a": b"1"}, class_set=CLASS_SET, obsolete_key=key("old")
        )
        assert reply == 1
        assert backend.load_record(key("old")) is None
        assert backend.load_record(key("new")) == {b"a": b"1"}
        assert backend.list_keys(CLASS_SET) == {key("new")}

    def test_obsolete_key_equal_to_the_key_is_a_no_op(self, backend):
        backend.save_record(key("new"), {b"a": b"1"}, class_set=CLASS_SET)
        reply = backend.save_record(
            key("new"), {b"a": b"1"}, class_set=CLASS_SET, obsolete_key=key("new")
        )
        assert reply == 0
        assert backend.load_record(key("new")) == {b"a": b"1"}
        assert backend.list_keys(CLASS_SET) == {key("new")}

    def test_no_class_set_leaves_the_set_alone(self, backend):
        # protocol-2 (#735 review B1): ``class_set=None`` registers nothing and
        # un-registers nothing; the obsolete record is still removed.
        backend.save_record(key("old"), {b"a": b"1"}, class_set=CLASS_SET)
        assert backend.save_record(key("p"), {b"a": b"1"}) == 1
        assert backend.save_record(key("p"), {b"a": b"1"}) == 0
        assert backend.save_record(key("p"), {}) == 0
        assert backend.list_keys(CLASS_SET) == {key("old")}
        reply = backend.save_record(key("q"), {b"b": b"2"}, obsolete_key=key("old"))
        assert reply == 1
        assert backend.load_record(key("old")) is None
        assert backend.load_record(key("q")) == {b"b": b"2"}
        assert backend.list_keys(CLASS_SET) == {key("old")}, "SREM skipped too"
        uow = backend.begin()
        assert backend.save_record(key("p"), {b"c": b"3"}, uow=uow) is None
        assert uow.commit() == [1]
        assert backend.list_keys(CLASS_SET) == {key("old")}

    def test_numeric_side_map_is_accepted_and_does_not_change_the_payload(
        self, backend, backend_is_redis
    ):
        fields = {b"n": msgpack.packb(2.5), b"s": msgpack.packb("x")}
        assert (
            backend.save_record(key(1), fields, class_set=CLASS_SET, numeric={"n": 2.5})
            == 2
        )
        assert backend.load_record(key(1)) == fields
        if not backend_is_redis:
            rows = (
                backend._connection()
                .execute(
                    "SELECT field, value FROM popoto_numeric WHERE key = %s",
                    (key(1),),
                )
                .fetchall()
            )
            assert rows == [("n", 2.5)]
            backend.delete_record(key(1), class_set=CLASS_SET)
            rows = (
                backend._connection()
                .execute("SELECT 1 FROM popoto_numeric WHERE key = %s", (key(1),))
                .fetchall()
            )
            assert rows == []


# -- C. Atomic increment --------------------------------------------------------

ABSENT = object()


def f64(value: float) -> bytes:
    return struct.pack(">Bd", 0xCB, value)


def f32(value: float) -> bytes:
    return struct.pack(">Bf", 0xCA, value)


#: (stored payload before, kind, delta, expected return, expected stored).
#: ``expected stored`` is the raw bytes for int/float kinds and the
#: ``as_encodable`` text for the Decimal envelope. Recorded from the Redis
#: path (``ATOMIC_INCREMENT_LUA``): Lua 5.1 renders returns with ``%.14g``,
#: cmsgpack packs an integral double as an integer and a fractional one as
#: float32 when lossless else float64, and anything that is not a number (or
#: a tagged map for a Decimal increment) counts as ``0``.
INCREMENT_CASES: list[tuple[Any, str, Any, Any, Any]] = [
    (ABSENT, "int", 5, 5, msgpack.packb(5)),
    (10, "int", 5, 15, msgpack.packb(15)),
    (-7, "int", -3, -10, msgpack.packb(-10)),
    (2**40, "int", 1, 2**40 + 1, msgpack.packb(2**40 + 1)),
    (0.5, "int", 1, 1, f32(1.5)),
    ({"__Decimal__": True, "as_encodable": "2"}, "int", 1, 1, msgpack.packb(1)),
    ("hello", "int", 1, 1, msgpack.packb(1)),
    (True, "int", 1, 1, msgpack.packb(1)),
    (None, "int", 1, 1, msgpack.packb(1)),
    ([1, 2], "int", 1, 1, msgpack.packb(1)),
    (1.5, "float", 1.5, 3.0, msgpack.packb(3)),
    (2.5, "float", -2.5, 0.0, msgpack.packb(0)),
    (1, "float", 0.5, 1.5, f32(1.5)),
    (1, "float", 1.0, 2.0, msgpack.packb(2)),
    (0.1, "float", 0.2, 0.3, f64(0.1 + 0.2)),
    (1.0, "float", 0.1, 1.1, f64(1.0 + 0.1)),
    (ABSENT, "float", 2.25, 2.25, f32(2.25)),
    (ABSENT, "float", 1 / 3, 0.33333333333333, f64(1 / 3)),
    (ABSENT, "float", 1e14, 1e14, msgpack.packb(10**14)),
    (ABSENT, "float", 1e20, 1e20, f64(1e20)),
    (ABSENT, "float", 1e300, 1e300, f64(1e300)),
    (
        {"__Decimal__": True, "as_encodable": "10.5"},
        "decimal",
        Decimal("1.25"),
        Decimal("11.75"),
        "11.75",
    ),
    (ABSENT, "decimal", Decimal("1.25"), Decimal("1.25"), "1.25"),
    (3, "decimal", Decimal("1"), Decimal("4"), "4"),
    (1.5, "decimal", Decimal("0.25"), Decimal("1.75"), "1.75"),
    (
        {"__Decimal__": True, "as_encodable": 7},
        "decimal",
        Decimal("1"),
        Decimal("8"),
        "8",
    ),
    (ABSENT, "decimal", Decimal("0.0000001"), Decimal("1E-7"), "1e-07"),
    (
        ABSENT,
        "decimal",
        Decimal("123456789.123456789"),
        Decimal("123456789.12346"),
        "123456789.12346",
    ),
]


class TestIncrement:
    @pytest.mark.parametrize(
        ("initial", "kind", "delta", "expected", "stored"),
        INCREMENT_CASES,
        ids=[
            f"{kind}:{initial!r}+{delta!r}"
            for initial, kind, delta, _, _ in INCREMENT_CASES
        ],
    )
    def test_increment_matches_the_lua_envelope(
        self, backend, initial, kind, delta, expected, stored
    ):
        k = key("inc")
        if initial is not ABSENT:
            backend.save_record(k, {b"n": msgpack.packb(initial)}, class_set=CLASS_SET)
        got = backend.increment_field(k, "n", delta, kind=kind)
        assert got == expected
        assert type(got) is type(expected)
        raw = backend.load_record(k)[b"n"]
        if kind == "decimal":
            assert msgpack.unpackb(raw, raw=False) == {
                "__Decimal__": True,
                "as_encodable": stored,
            }
        else:
            assert raw == stored

    def test_increments_chain(self, backend):
        k = key("inc")
        assert backend.increment_field(k, "n", 1, kind="int") == 1
        assert backend.increment_field(k, "n", 2, kind="int") == 3
        assert backend.increment_field(k, "n", -5, kind="int") == -2
        assert msgpack.unpackb(backend.load_record(k)[b"n"]) == -2

    def test_absent_record_gains_the_field_but_no_class_set_entry(self, backend):
        k = key("inc")
        assert not backend.record_exists(k)
        assert backend.increment_field(k, "n", 1, kind="int") == 1
        assert backend.record_exists(k)
        assert backend.load_record(k) == {b"n": msgpack.packb(1)}
        assert k not in backend.list_keys(CLASS_SET)

    def test_an_unparseable_decimal_envelope_is_an_error(self, backend):
        k = key("inc")
        backend.save_record(
            k,
            {b"n": msgpack.packb({"__Decimal__": True, "as_encodable": "abc"})},
            class_set=CLASS_SET,
        )
        with pytest.raises(Exception):
            backend.increment_field(k, "n", Decimal("1"), kind="decimal")

    def test_queued_on_a_unit_of_work(self, backend):
        k = key("inc")
        uow = backend.begin()
        assert backend.increment_field(k, "n", 5, kind="int", uow=uow) is None
        assert backend.load_record(k) is None, "nothing may be written before commit()"
        results = uow.commit()
        assert isinstance(results, list) and results
        assert backend.load_record(k) == {b"n": msgpack.packb(5)}

    def test_a_concurrent_save_from_another_instance_cannot_be_lost(
        self, backend, backend_is_redis, monkeypatch
    ):
        """Cross-instance serialisation of ``increment_field`` against
        ``save_record`` on the same key (PR #737 review, B1).

        Instance A increments ``n`` on a record that does not exist yet.
        Between A's "no row" read and its upsert, instance B (a second
        backend, so a second connection) saves ``n = 100``. The only serial
        outcomes are ``100`` (increment, then save) and ``101`` (save, then
        increment); Redis's single thread can produce nothing else. Without a
        lock shared by both operations A's upsert lands on B's committed row
        and overwrites it with ``0 + 1``, a value no serial order produces.

        The interleaving is forced deterministically: ``_current_value`` is
        hooked to run B's save on a thread while A is mid-transaction, and the
        hook returns only once that save has either committed (the lost-update
        shape) or is blocked on A's lock in ``pg_stat_activity`` (the fixed
        shape). Postgres-leg only: the Redis Lua has no hook point and needs
        none.
        """
        if backend_is_redis:
            pytest.skip("Postgres-leg assertion: Redis serialises these natively")
        import psycopg

        k = key("race")
        other = PostgresBackend(backend.url)
        probe = psycopg.connect(backend.url, autocommit=True)
        other_pid = other._connection().info.backend_pid
        save_errors: list[BaseException] = []

        def save_from_b() -> None:
            try:
                other.save_record(k, {b"n": msgpack.packb(100)}, class_set=CLASS_SET)
            except BaseException as exc:  # surfaced by the assertion below
                save_errors.append(exc)

        saver = threading.Thread(target=save_from_b, name="instance-B-save")
        real_current_value = postgres_module._current_value

        def hooked_current_value(packed, is_decimal):
            # Fire once: A has read "no row" and is inside its transaction.
            monkeypatch.setattr(postgres_module, "_current_value", real_current_value)
            saver.start()
            deadline = time.monotonic() + 10.0
            while saver.is_alive() and time.monotonic() < deadline:
                row = probe.execute(
                    "SELECT wait_event_type FROM pg_stat_activity WHERE pid = %s",
                    (other_pid,),
                ).fetchone()
                if row is not None and row[0] == "Lock":
                    break  # B is queued behind A's advisory lock
                time.sleep(0.01)
            else:
                assert not saver.is_alive(), "B neither committed nor blocked"
            return real_current_value(packed, is_decimal)

        monkeypatch.setattr(postgres_module, "_current_value", hooked_current_value)
        try:
            got = backend.increment_field(k, "n", 1, kind="int")
            saver.join(timeout=10.0)
            assert not saver.is_alive(), "B's save never completed after A committed"
        finally:
            probe.close()
            other.close()
        assert not save_errors, f"B's save_record raised: {save_errors[0]!r}"
        assert got in (1, 101)
        final = msgpack.unpackb(backend.load_record(k)[b"n"])
        assert final in (
            100,
            101,
        ), f"lost update: stored n={final}; a serial order gives 100 or 101"


# -- J. Orphan purge ------------------------------------------------------------

ZIDX = f"{PREFIX}:_score"
SIDX = f"{PREFIX}:_tag:x"


class TestPurgeOrphan:
    def test_leaves_a_live_records_memberships_alone(self, backend):
        k = key(1)
        backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET)
        seed_index(backend, ZIDX, "sorted", k)
        seed_index(backend, SIDX, "set", k)
        assert backend.purge_orphan(k, [(ZIDX, "sorted"), (SIDX, "set")]) == 0
        assert index_has(backend, ZIDX, "sorted", k)
        assert index_has(backend, SIDX, "set", k)

    def test_removes_a_gone_records_memberships_and_counts_them(self, backend):
        k = key("gone")
        seed_index(backend, ZIDX, "sorted", k)
        seed_index(backend, SIDX, "set", k)
        refs = [(ZIDX, "sorted"), (SIDX, "set"), (f"{PREFIX}:_never", "set")]
        assert backend.purge_orphan(k, refs) == 2
        assert not index_has(backend, ZIDX, "sorted", k)
        assert not index_has(backend, SIDX, "set", k)
        assert backend.purge_orphan(k, refs) == 0
        assert backend.purge_orphan(k, []) == 0

    def test_only_the_named_refs_are_touched(self, backend):
        k = key("gone")
        other = f"{SIDX}:other"
        seed_index(backend, SIDX, "set", k)
        seed_index(backend, other, "set", k)
        seed_index(backend, SIDX, "set", key("neighbour"))
        assert backend.purge_orphan(k, [(SIDX, "set")]) == 1
        assert not index_has(backend, SIDX, "set", k)
        assert index_has(backend, other, "set", k)
        assert index_has(backend, SIDX, "set", key("neighbour"))

    def test_a_record_that_came_back_is_not_purged(self, backend):
        k = key("back")
        seed_index(backend, ZIDX, "sorted", k)
        backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET)
        assert backend.purge_orphan(k, [(ZIDX, "sorted")]) == 0
        assert index_has(backend, ZIDX, "sorted", k)

    def test_queued_on_a_unit_of_work(self, backend):
        k = key("gone")
        seed_index(backend, SIDX, "set", k)
        uow = backend.begin()
        assert backend.purge_orphan(k, [(SIDX, "set")], uow=uow) is None
        assert index_has(backend, SIDX, "set", k), "nothing may run before commit()"
        uow.commit()
        assert not index_has(backend, SIDX, "set", k)


# -- A. Unit of work ------------------------------------------------------------


class TestUnitOfWork:
    def test_queued_methods_return_none_and_write_nothing_before_commit(self, backend):
        k = key(1)
        uow = backend.begin()
        assert (
            backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET, uow=uow) is None
        )
        assert backend.increment_field(k, "n", 1, kind="int", uow=uow) is None
        assert backend.delete_record(key("x"), class_set=CLASS_SET, uow=uow) is None
        assert backend.purge_orphan(key("x"), [], uow=uow) is None
        assert backend.load_record(k) is None
        assert not backend.record_exists(k)
        assert backend.list_keys(CLASS_SET) == set()
        uow.reset()

    def test_commit_applies_the_queue_in_order_and_returns_a_list(self, backend):
        k, other = key(1), key("other")
        backend.save_record(other, {b"a": b"1"}, class_set=CLASS_SET)
        with backend.begin() as uow:
            backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET, uow=uow)
            backend.increment_field(k, "n", 2, kind="int", uow=uow)
            backend.delete_record(other, class_set=CLASS_SET, uow=uow)
            results = uow.commit()
        assert isinstance(results, list) and results
        assert backend.load_record(k) == {b"a": b"1", b"n": msgpack.packb(2)}
        assert backend.load_record(other) is None
        assert backend.list_keys(CLASS_SET) == {k}

    def test_leaving_the_block_without_commit_discards_the_queue(self, backend):
        k = key(1)
        with backend.begin() as uow:
            backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET, uow=uow)
        assert backend.load_record(k) is None
        assert backend.list_keys(CLASS_SET) == set()

    def test_an_exception_inside_the_block_discards_the_queue(self, backend):
        k = key(1)
        with pytest.raises(RuntimeError):
            with backend.begin() as uow:
                backend.save_record(k, {b"a": b"1"}, class_set=CLASS_SET, uow=uow)
                raise RuntimeError("boom")
        assert backend.load_record(k) is None

    def test_commit_empties_the_queue(self, backend):
        uow = backend.begin()
        backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET, uow=uow)
        assert uow.commit(), "one reply per op (Postgres) or per command (Redis)"
        assert uow.commit() == []
        assert backend.load_record(key(1)) == {b"a": b"1"}

    def test_a_rolled_back_save_is_not_visible(self, backend):
        """The committed state of a second unit of work after the first was
        abandoned: only the second's writes exist."""
        with backend.begin() as abandoned:
            backend.save_record(
                key("rolled"), {b"a": b"1"}, class_set=CLASS_SET, uow=abandoned
            )
        with backend.begin() as uow:
            backend.save_record(key("kept"), {b"a": b"1"}, class_set=CLASS_SET, uow=uow)
            uow.commit()
        assert backend.load_record(key("rolled")) is None
        assert backend.load_record(key("kept")) == {b"a": b"1"}
        assert backend.list_keys(CLASS_SET) == {key("kept")}


# -- What WS3a does *not* implement ---------------------------------------------


class TestScope:
    def test_ttl_is_honoured_on_redis_and_refused_on_postgres(
        self, backend, backend_is_redis
    ):
        if backend_is_redis:
            backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET, ttl=100)
            assert 0 < backend.client.ttl(key(1)) <= 100
            return
        with pytest.raises(NotImplementedError, match="TTL"):
            backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET, ttl=100)
        with pytest.raises(NotImplementedError, match="TTL"):
            backend.save_record(
                key(1), {b"a": b"1"}, class_set=CLASS_SET, expire_at=4102444800.0
            )
        assert backend.load_record(key(1)) is None

    def test_set_expiry_is_honoured_on_redis_and_refused_on_postgres(
        self, backend, backend_is_redis
    ):
        # protocol-2 (#735 review B2). A record without a TTL asks for nothing
        # on either backend, which is what Model.save's partial path issues
        # for a Meta without ``ttl``.
        backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET)
        assert backend.set_expiry(key(1)) is None
        uow = backend.begin()
        assert backend.set_expiry(key(1), uow=uow) is None
        assert uow.commit() == []
        if backend_is_redis:
            assert backend.set_expiry(key(1), ttl=100) is True
            assert 0 < backend.client.ttl(key(1)) <= 100
            return
        with pytest.raises(NotImplementedError, match="TTL"):
            backend.set_expiry(key(1), ttl=100)
        with pytest.raises(NotImplementedError, match="TTL"):
            backend.set_expiry(key(1), expire_at=4102444800.0, uow=backend.begin())
        assert backend.load_record(key(1)) == {b"a": b"1"}

    def test_other_families_still_raise_on_postgres(self, backend, backend_is_redis):
        # Families D, E, F and the rest of J are WS3b's and implemented (see
        # ``test_indexes.py``); G, H, I and B's ``records_exist`` still raise.
        if backend_is_redis:
            pytest.skip("Postgres-leg assertion")
        with pytest.raises(NotImplementedError, match=r"PostgresBackend\.swap_index"):
            backend.swap_index(key(1), "f", ZIDX, b"v", unique=False)
        with pytest.raises(NotImplementedError, match=r"PostgresBackend\.decayed_rank"):
            backend.decayed_rank(
                ZIDX, now=0.0, decay_rate=0.1, limit=None, pretrim_max_ratio=1.0
            )
        with pytest.raises(
            NotImplementedError, match=r"PostgresBackend\.records_exist"
        ):
            backend.records_exist([key(1)])
        with pytest.raises(NotImplementedError, match=r"PostgresBackend\.supersede"):
            backend.supersede(
                "$ValidityF:M",
                "f",
                mode="close",
                new_member="x",
                now=0.0,
                valid_from=None,
                ingested_at=None,
                close_at=None,
                assert_valid_from=False,
                pointer_digest=None,
            )
        with pytest.raises(NotImplementedError, match="Redis-only"):
            backend.native()

    def test_a_foreign_unit_of_work_is_rejected_on_postgres(
        self, backend, backend_is_redis
    ):
        if backend_is_redis:
            pytest.skip("Postgres-leg assertion")
        with pytest.raises(TypeError):
            backend.save_record(key(1), {b"a": b"1"}, class_set=CLASS_SET, uow=object())
