site_name: Popoto Documentation
repo_url: https://github.com/tomcounsell/popoto/
site_author: Tom Counsell

nav:
    - Home: 'index.md'
    - Models and Fields: 'fields.md'
    - Making Queries: 'query.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - markdown
        - python
        - bash
        - html
