site_name: Popoto Documentation
repo_url: https://github.com/tomcounsell/popoto/
edit_uri: edit/master/docs
site_author: Tom Counsell

nav:
    - Home: 'index.md'
    - Models and Fields: 'fields.md'
    - Making Queries: 'query.md'
    - Relationship Field: 'relationship.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - markdown
        - python
        - bash
        - html
    collapse_navigation: False
    sticky_navigation: True
