site_name: Popoto Documentation
repo_url: https://github.com/tomcounsell/popoto/
edit_uri: edit/master/docs
site_author: Tom Counsell

nav:
    - Home: 'index.md'
    - Configuration: 'configuration.md'
    - Models and Fields: 'fields.md'
    - Model Meta Options: 'meta.md'
    - Making Queries: 'query.md'
    - Relationship Field: 'relationship.md'
    - Multi-Tenancy: 'multi-tenancy.md'
    - Async Operations: 'async.md'
    - PubSub: 'pubsub.md'
    - API Reference: 'api-reference.md'
    - Contributing:
        - Style Guide: 'style-guide.md'

markdown_extensions:
    - admonition

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - markdown
        - python
        - bash
        - html
    collapse_navigation: False
    sticky_navigation: True
