site_name: Popoto - A Redis ORM - Documentation
repo_url: https://github.com/tomcounsell/popoto/
site_author: Tom Counsell

nav:
    - Home: 'index.md'
    - Models and Fields: 'fields.md'
    - Making Queries: 'query.md'
