# Generated by Django 3.1.4 on 2021-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210118_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='quantity_offline',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='alternative_symbols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
