# Generated by Django 3.1.4 on 2021-01-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201208_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
