"""
Indexed Field Mixin - Secondary Indexing for Non-Key Fields
============================================================

This module provides the IndexedFieldMixin class, which enables exact-match
secondary indexing on fields that are NOT part of the model's Redis key.

Design Philosophy
-----------------
KeyField conflates two concerns: identity (forming the Redis storage key) and
indexing (enabling queries). IndexedFieldMixin decouples these by providing
Set-based indexing without making the field part of the Redis key (identity).

This allows developers to query on fields like ``email``, ``status``, or
``category`` without making them part of the model's identity.

The implementation follows the exact same pattern as KeyFieldMixin:
- ``on_save()``: Maintains an index at ``$IndexF:Model:field_name:value``
- ``on_delete()``: Removes from the index
- ``filter_query()``: Uses set-index lookups (SMEMBERS/SUNION on Redis)
- ``get_filter_query_params()``: Declares supported query lookups

Index Key Pattern
-----------------
    $IndexF:ModelName:field_name:value -> Set of redis_keys

This mirrors the ``$KeyF`` pattern used by KeyFieldMixin but uses the
``$IndexF`` prefix (auto-generated by FieldBase metaclass via ``field_class_key``).

Storage seam (#631 WS1c)
------------------------
Every storage operation here goes through :func:`popoto.backends.get_backend`:
the atomic check-and-swap is :meth:`~popoto.backends.Backend.swap_index`, the
delete-side cleanup is :meth:`~popoto.backends.Backend.drop_index_entry`, and
the filter lookups are the set-index family (``index_members``,
``index_union``, ``scan_index_names``). On Redis those are today's commands,
moved verbatim into :class:`popoto.backends.redis.RedisBackend` --
``INDEX_SWAP_LUA`` included, re-exported below under its old name. The
``$IdxPtr:`` pointer side key, its pre-#540 variant and the pre-#476 in-hash
pointer are Redis key-layout migration state the backend derives from
``(record_key, field)``; this module no longer passes them.

Usage
-----
    from popoto import Model, Field
    from popoto.fields.shortcuts import IndexedField, UniqueField

    class User(Model):
        user_id = AutoKeyField()
        email = UniqueField(type=str)       # indexed + unique
        status = IndexedField(type=str)     # indexed, not unique

    # Efficient exact-match queries without making email a KeyField
    User.query.filter(email="alice@example.com")
    User.query.filter(status="active")
    User.query.filter(status__in=["active", "pending"])
"""

import logging
from typing import TYPE_CHECKING, Any, Iterable
import msgpack

from ..backends import get_backend
from ..exceptions import ModelException, QueryException
from ..models.db_key import DB_key
from ..redis_db import ENCODING

if TYPE_CHECKING:  # pragma: no cover - import cycle guard
    from ..models.base import Model

logger = logging.getLogger("POPOTO.IndexedFieldMixin")

# ``pipeline=`` is duck-typed (#631 architect decision 1): the field layer
# only asks ``is not None`` and hands it to the backend as ``uow=``. On Redis
# it is the ``GuardedPipeline``. It is annotated ``Any`` rather than
# ``UnitOfWork | None`` because ``Field.on_save``/``on_delete`` still annotate
# ``redis.client.Pipeline``, and mypy rejects a narrower type here as an
# incompatible multiple-inheritance definition on ``IndexedField`` /
# ``UniqueField`` / ``TagField`` in ``shortcuts.py``, which this slice does
# not own.

# Sentinel used to distinguish "field not in saved_values" from "field was None".
# This matters for the legacy-old-set hint: when old_value is None (the field
# was stored as None before), we still want to emit the SREM hint so that legacy
# records (without a server-authoritative pointer) can be cleaned up correctly.
_SENTINEL = object()


# ``INDEX_SWAP_LUA`` moved to ``popoto.backends.redis`` (#631 WS0).
# It is re-imported here under its existing name so every current
# reader -- the tests that import it from here, and
# ``tests/test_transfer_roundtrip.py``'s source scan -- keeps finding it.
# The script text itself is byte-identical; since WS1c this module no
# longer runs it, ``RedisBackend.swap_index`` does.
from ..backends.redis import INDEX_SWAP_LUA  # noqa: E402,F401


def _members_as_bytes(members: Iterable[str]) -> set[bytes]:
    """Re-encode the backend's decoded ``str`` members to ``bytes``.

    The backend decodes every set-index reply to ``str`` (#732 deviation 11),
    but ``Query.filter_for_keys_set`` intersects this field's result with
    what ``KeyFieldMixin`` and ``SortedFieldMixin`` return, and those are the
    raw ``bytes`` replies until WS1b routes them. A ``str`` set intersected
    with a ``bytes`` set is empty, so a query composing a KeyField filter
    with an IndexedField filter would silently match nothing. Keeping the
    pre-seam ``bytes`` shape at this boundary makes the result independent
    of which of WS1b / WS1c merges first; flipping the whole field layer to
    ``str`` is one later PR across the four mixins and ``Query.keys``.
    """
    return {m.encode(ENCODING) for m in members}


class IndexedFieldMixin:
    """
    Mixin that provides Set-based secondary indexing for non-key fields.

    When mixed with Field, this mixin maintains an index per field value that
    tracks which model instances carry that value. This enables efficient
    exact-match queries without making the field part of the model's key
    (identity).

    Supports the same query lookups as KeyFieldMixin:
    - Exact match: ``filter(field=value)``
    - IN queries: ``filter(field__in=[v1, v2])``
    - Null checks: ``filter(field__isnull=True/False)``
    - Pattern matching: ``filter(field__startswith="prefix")``
    - Pattern matching: ``filter(field__endswith="suffix")``

    Uniqueness enforcement is available via ``unique=True``. The check is
    performed inside the backend's atomic ``swap_index`` (on Redis, the
    INDEX_SWAP_LUA script), eliminating the classic check-then-act race
    condition.

    When an external pipeline is provided, a best-effort pre-check is made
    before queuing the swap. The authoritative uniqueness guarantee is only
    enforced at pipeline.execute() time, when the swap runs atomically on
    the server.

    Attributes:
        indexed (bool): Always True for indexed fields.
    """

    indexed: bool = True

    # Export/import: the atomic index Set/pointer is fully rebuilt from the
    # field value by on_save() (via the backend's swap_index), so nothing
    # needs to be carried across export/import.
    roundtrip_policy: str = "rebuild"

    # The three key builders below are the Redis key layout the backend
    # derives for itself (``popoto.backends.redis._idx_ptr_key`` and
    # friends). This module no longer passes them to anything; they stay as
    # documented, test-visible helpers (``tests/test_issue_540_*`` and
    # ``tests/test_concurrent_index_integrity.py`` plant and inspect these
    # keys) and must stay byte-equal to the backend's builders.

    @staticmethod
    def _pointer_side_key(model_hash_key: str, field_name: str) -> str:
        """Build the side key that stores the server-authoritative index pointer.

        This is a standalone Redis key (STRING type), NOT a field inside the
        model hash — see #476.

        It is namespaced under ``$IdxPtr:``, alongside Popoto's other internal
        keys (``$Class:``, ``$KeyF:``, ``$SortedF:``), so it lives outside
        every model's own key space. 1.8.1/1.8.2 instead derived it by
        suffixing the model hash key with ``\\x00idxptr\\x00{field}`` on the
        theory that a NUL byte keeps it out of user-written globs. It does
        not: Redis glob ``*`` matches any byte, NUL included, so that key was
        matched by every pattern matching the hash key itself. The concrete
        casualty was ``AutoKeyField`` lookup — the one KeyField path with no
        index Set, which resolves via ``scan_keys`` over exactly that glob
        (see ``KeyFieldMixin.filter_query``). It picked up the STRING pointer
        keys and the follow-up HGETALL failed with WRONGTYPE (#540).

        A model name can never begin with ``$``, so this key can never be
        matched by a model key glob. ``field_name`` is a Python identifier and
        cannot contain ``:``, so the trailing segment stays unambiguous.
        """
        return f"$IdxPtr:{model_hash_key}:{field_name}"

    @staticmethod
    def _pre_540_pointer_side_key(model_hash_key: str, field_name: str) -> str:
        """The 1.8.1/1.8.2 pointer side key. Read-only migration fallback.

        Never written by current code. Read once and then DEL'd (in
        INDEX_SWAP_LUA and drop_index_entry) so records written by those
        versions self-heal off the colliding key space without an offline
        migration.
        """
        return f"{model_hash_key}\x00idxptr\x00{field_name}"

    @staticmethod
    def _legacy_pointer_field(field_name: str) -> str:
        """Pre-#476 in-hash pointer field name, kept for migration fallback only.

        Never written by current code. Only read (and then scrubbed via HDEL
        inside INDEX_SWAP_LUA / drop_index_entry) so records written before
        this fix shipped continue to be cleaned up correctly, and self-heal
        off the polluted hash schema the first time they're touched again.
        """
        return f"{field_name}\x00idxset"

    def __init__(self, **kwargs):
        """
        Initialize IndexedFieldMixin defaults.

        Sets ``indexed=True`` and updates field_defaults for introspection.
        Calls super().__init__() for cooperative multiple inheritance.
        """
        super().__init__(**kwargs)
        indexed_defaults = {
            "indexed": True,
        }
        self.field_defaults.update(indexed_defaults)
        for k, v in indexed_defaults.items():
            setattr(self, k, kwargs.get(k, v))

    @staticmethod
    def _unique_conflict_message(
        model_instance: "Model", field_name: str, field_value: Any
    ) -> str:
        """The user-facing uniqueness error, byte-identical to the pre-seam text.

        The backend's ``swap_index`` raises its own ``ModelException`` naming
        ``record_key``/``field``/``new_idx`` (#732 deviation 6: it never sees
        ``Model.field`` or the raw value). Both raise sites here re-wrap it
        with this wording so callers keep seeing exactly what they saw before.
        """
        return (
            f"Uniqueness violation on "
            f"{model_instance.__class__.__name__}.{field_name}: "
            f"value '{field_value}' is already taken by another instance"
        )

    @classmethod
    def on_save(
        cls,
        model_instance: "Model",
        field_name: str,
        field_value,
        pipeline: Any = None,
        **kwargs,
    ):
        """
        Maintain the secondary index when a model instance is saved.

        Internal path (no pipeline): calls the backend's ``swap_index``
        directly. On Redis that is one INDEX_SWAP_LUA EVAL, which atomically
        reads the old-set pointer, removes the member from the old Set,
        enforces uniqueness (if configured), SADDs to the new Set, and writes
        the server-authoritative pointer and field bytes — all as a single
        Redis command. No separate round-trips; no race window.

        External path (pipeline provided): performs a best-effort
        ``index_members`` pre-check for fast early raise on uniqueness
        violation, then queues the swap on the caller's unit of work. The
        authoritative guarantee is enforced at execute() time when the swap
        runs on the server. The pre-check reduces latency for the common
        conflict case but cannot close the TOCTOU window because the caller
        controls execute().

        Args:
            model_instance: The Model instance being saved.
            field_name: The name of this field on the model.
            field_value: The value being saved for this field.
            pipeline: Optional unit of work (a Redis pipeline on Redis) for
                batched operations. When provided, the swap is queued on it.
                When omitted, the swap executes now, atomically.

        Returns:
            The pipeline (if provided) or 1 (the swap's reply on the
            internal path).

        Raises:
            ModelException: If unique=True and the value is already taken
                by a different instance. Raised immediately on the internal
                path; raised at execute() time on the external path.
        """
        field = model_instance._meta.fields[field_name]
        member_key = model_instance.db_key.redis_key

        # Compute the new index key for this field value
        new_set_key = DB_key(
            cls.get_special_use_field_db_key(model_instance, field_name),
            field_value,
        ).redis_key

        # Legacy-old-set hint: used on first post-upgrade save of records
        # that predate the server-authoritative pointer. The backend uses
        # this only when the pointer is absent (i.e., never been written by
        # the new code path).
        saved_values = getattr(model_instance, "_saved_field_values", {})
        old_value = saved_values.get(field_name, _SENTINEL)
        if old_value is not _SENTINEL and old_value != field_value:
            # Use the saved value (even if it was None) as the legacy SREM hint.
            # This handles legacy records (no server-authoritative pointer) where
            # the field was previously stored as None.
            legacy_old_set = DB_key(
                cls.get_special_use_field_db_key(model_instance, field_name),
                old_value,
            ).redis_key
        else:
            legacy_old_set = ""

        # Pack field value with msgpack to match encode_popoto_model_obj()
        # output. Types in TYPE_ENCODER_DECODERS (datetime, date, time,
        # Decimal, ...) are not natively serializable by msgpack, so they must
        # go through their registered encoder first — exactly as
        # encode_popoto_model_obj() does — otherwise packb() raises TypeError
        # and the bytes would not match the canonical hash encoding (#534).
        from ..models.encoding import TYPE_ENCODER_DECODERS

        if field_value is not None and field.type in TYPE_ENCODER_DECODERS:
            new_bytes = msgpack.packb(
                TYPE_ENCODER_DECODERS[field.type].encoder(field_value)
            )
        else:
            new_bytes = msgpack.packb(field_value)
        is_unique = bool(getattr(field, "unique", False))

        backend = get_backend()
        if pipeline is not None:
            # External pipeline path: best-effort pre-check for fast early raise
            if field_value is not None and is_unique:
                existing_members = backend.index_members(new_set_key)
                other_members = {m for m in existing_members if m != member_key}
                if other_members:
                    raise ModelException(
                        cls._unique_conflict_message(
                            model_instance, field_name, field_value
                        )
                    )
            # Queue the swap on the caller's unit of work — authoritative
            # check at execute()
            backend.swap_index(
                member_key,
                field_name,
                new_set_key,
                new_bytes,
                unique=is_unique,
                legacy_old_idx=legacy_old_set,
                uow=pipeline,
            )
            return pipeline
        else:
            # Internal path: execute the swap now. This runs atomically on
            # the server; no client-side race.
            try:
                return backend.swap_index(
                    member_key,
                    field_name,
                    new_set_key,
                    new_bytes,
                    unique=is_unique,
                    legacy_old_idx=legacy_old_set,
                )
            except ModelException:
                # Deviation 6: the backend's wording names the record key and
                # index; the user-facing message names Model.field and the
                # raw value, as it always has.
                raise ModelException(
                    cls._unique_conflict_message(
                        model_instance, field_name, field_value
                    )
                )

    @classmethod
    def on_delete(
        cls,
        model_instance: "Model",
        field_name: str,
        field_value,
        pipeline: Any = None,
        **kwargs,
    ):
        """
        Remove the model instance from the index on delete.

        The backend's ``drop_index_entry`` uses the server-authoritative
        pointer side key (#476) — if present — to determine which value-Set
        to remove from. It falls back to the legacy pre-#476 in-hash pointer
        field (for records written before this fix shipped), then to the
        field_value-derived key passed here as ``fallback_idx`` for records
        that predate any pointer at all.

        Important: this reads live storage state (GET/HGET on Redis), so it
        must be called BEFORE the model hash itself is deleted — see
        Model.delete() in base.py, which runs field.on_delete() hooks ahead
        of the hash DELETE for exactly this reason (#476 latent bug: reading
        the pointer after the hash was already gone always returned nothing,
        silently falling back to a possibly-stale in-memory snapshot).

        Args:
            model_instance: The Model instance being deleted.
            field_name: The name of this field on the model.
            field_value: The value stored for this field.
            pipeline: Optional unit of work for batched operations.

        Returns:
            The pipeline (if provided) or the removal result (the SREM reply
            on Redis).
        """
        member_key = kwargs.get("saved_redis_key", model_instance.db_key.redis_key)

        # No pointer found anywhere: the backend falls back to the
        # field_value-derived key.
        fallback_idx = DB_key(
            cls.get_special_use_field_db_key(model_instance, field_name),
            field_value,
        ).redis_key

        backend = get_backend()
        if pipeline is not None:
            backend.drop_index_entry(
                member_key, field_name, fallback_idx=fallback_idx, uow=pipeline
            )
            return pipeline
        return backend.drop_index_entry(
            member_key, field_name, fallback_idx=fallback_idx
        )

    def get_filter_query_params(self, field_name: str) -> set:
        """
        Return the set of valid query parameter names for filtering on this field.

        Supports the same lookups as KeyFieldMixin:
        - exact match
        - __in
        - __isnull
        - __startswith
        - __endswith

        Args:
            field_name: The name of this field on the model.

        Returns:
            set: Valid query parameter strings.
        """
        return (
            super()
            .get_filter_query_params(field_name)
            .union(
                {
                    f"{field_name}",
                    f"{field_name}__isnull",
                    f"{field_name}__startswith",
                    f"{field_name}__endswith",
                    f"{field_name}__in",
                }
            )
        )

    @classmethod
    def filter_query(cls, model: "Model", field_name: str, **query_params) -> set:
        """
        Execute a filter query on this indexed field and return matching Redis keys.

        Uses set-index lookups for exact match and __in queries. Falls back
        to an index-name scan for pattern queries (__startswith, __endswith).

        Args:
            model: The Model class being queried.
            field_name: The name of this field on the model.
            **query_params: Dict mapping query parameter names to values.

        Returns:
            set: Redis keys (as bytes) of matching model instances.

        Raises:
            QueryException: If __isnull receives a non-boolean value.
        """
        keys_lists_to_intersect = list()

        redis_set_key_prefix = model._meta.fields[
            field_name
        ].get_special_use_field_db_key(model, field_name)
        backend = get_backend()

        for query_param, query_value in query_params.items():
            if query_param.endswith("__in"):
                # Server-side set union (SUNION on Redis)
                set_keys = [
                    DB_key(redis_set_key_prefix, query_value_elem).redis_key
                    for query_value_elem in query_value
                ]
                if set_keys:
                    keys_lists_to_intersect.append(
                        _members_as_bytes(backend.index_union(set_keys))
                    )
                else:
                    keys_lists_to_intersect.append(set())

            elif query_param == f"{field_name}":
                keys_lists_to_intersect.append(
                    _members_as_bytes(
                        backend.index_members(
                            DB_key(redis_set_key_prefix, query_value).redis_key
                        )
                    )
                )

            elif query_param.endswith("__isnull"):
                if query_value is True:
                    keys_lists_to_intersect.append(
                        _members_as_bytes(
                            backend.index_members(
                                DB_key(redis_set_key_prefix, None).redis_key
                            )
                        )
                    )
                elif query_value is False:
                    # Scan all index names for this field, then union
                    pattern = f"{redis_set_key_prefix.redis_key}:*"
                    all_keys = backend.scan_index_names(pattern)
                    # Filter out the None set
                    none_key = DB_key(redis_set_key_prefix, None).redis_key
                    non_null_keys: set[str] = set()
                    for key_str in all_keys:
                        if key_str != none_key:
                            non_null_keys.update(backend.index_members(key_str))
                    keys_lists_to_intersect.append(_members_as_bytes(non_null_keys))
                else:
                    raise QueryException(f"{query_param} filter must be True or False")

            elif query_param.endswith("__startswith"):
                # Scan index names matching the prefix pattern
                pattern = (
                    f"{redis_set_key_prefix.redis_key}:{DB_key.clean(query_value)}*"
                )
                matching_index_keys = backend.scan_index_names(pattern)
                members: set[str] = set()
                for idx_key in matching_index_keys:
                    members.update(backend.index_members(idx_key))
                keys_lists_to_intersect.append(_members_as_bytes(members))

            elif query_param.endswith("__endswith"):
                # Scan index names matching the suffix pattern
                pattern = (
                    f"{redis_set_key_prefix.redis_key}:*{DB_key.clean(query_value)}"
                )
                matching_index_keys = backend.scan_index_names(pattern)
                members = set()
                for idx_key in matching_index_keys:
                    members.update(backend.index_members(idx_key))
                keys_lists_to_intersect.append(_members_as_bytes(members))

        logger.debug(keys_lists_to_intersect)
        if len(keys_lists_to_intersect):
            return set.intersection(
                *[set(key_list) for key_list in keys_lists_to_intersect]
            )
        return set()
